import React from 'react';
import { Link, useParams } from 'react-router-dom';
import { motion } from 'framer-motion';
import { MapPin, Calendar } from 'lucide-react';
// This data would normally be fetched, but for now we import it directly
const tripsDataForDetail = [ 
    { id: "1", title: "Journey to the Danakil Depression", author: "Alex M.", imageUrl: "https://images.unsplash.com/photo-1518684079-3c830dcef090?q=80&w=2787&auto=format&fit=crop", location: "Afar Region, Ethiopia", date: "October 2024", description: "An unforgettable expedition to one of the most surreal and extreme landscapes on Earth. We witnessed otherworldly sulphur springs, vast salt flats, and the glowing lava lake of the Erta Ale volcano. A true test of endurance and a visual feast.", gallery: ["https://images.unsplash.com/photo-1548872545-3C534a742134?q=80&w=2787&auto=format&fit=crop", "https://images.unsplash.com/photo-1617751139145-a37a2629ff58?q=80&w=2835&auto=format&fit=crop", "https://images.unsplash.com/photo-1598179883995-1216b0a85a49?q=80&w=2835&auto=format&fit=crop"] },
    { id: "2", title: "Trekking the Simien Mountains", author: "Selam T.", imageUrl: "https://images.unsplash.com/photo-1606243403755-9ab377196434?q=80&w=2831&auto=format&fit=crop", location: "Amhara Region, Ethiopia", date: "November 2024", description: "Three days spent hiking through the breathtaking 'Roof of Africa'. Encountered massive troops of Gelada monkeys and spotted the elusive Walia Ibex on the sheer cliffs. The views from Imet Gogo were simply life-changing.", gallery: ["https://images.unsplash.com/photo-1617992933719-2169ac965451?q=80&w=2787&auto=format&fit=crop", "https://www.discover-afrika.com/wp-content/uploads/2021/03/Gelada-Baboon-Ethiopia-e1616782236968.jpg", "https://i.natgeofe.com/n/a9296359-3319-48d7-84d3-317429a25993/walia-ibex_thumb_3x2.jpg"] },
    { id: "3", title: "Churches of Lalibela", author: "David B.", imageUrl: "https://images.unsplash.com/photo-1605599443424-857f12e60421?q=80&w=2787&auto=format&fit=crop", location: "Amhara Region, Ethiopia", date: "August 2024", description: "A spiritual journey back in time, exploring the incredible rock-hewn churches of Lalibela. Each structure, carved from a single piece of stone, tells a story of faith and incredible craftsmanship. A humbling and awe-inspiring experience.", gallery: ["https://images.unsplash.com/photo-1578637387413-8199344f65c2?q=80&w=2787&auto=format&fit=crop", "https://images.unsplash.com/photo-1662952945209-6a3f133036e4?q=80&w=2799&auto=format&fit=crop", "https://images.unsplash.com/photo-1662952945455-3b1a1a2b2e8e?q=80&w=2799&auto=format&fit=crop"] },
    { id: "4", title: "Exploring the Omo Valley", author: "Aman F.", imageUrl: "https://images.unsplash.com/photo-1596922813971-f930a8a62319?q=80&w=2787&auto=format&fit=crop", location: "SNNPR, Ethiopia", date: "September 2024", description: "Met with the incredible tribes of the Omo Valley, including the Mursi and Hamar people. It was a profound cultural experience, learning about ancient traditions and ways of life that have remained unchanged for centuries.", gallery: ["https://images.unsplash.com/photo-1596792476906-e7f369f44358?q=80&w=2787&auto=format&fit=crop", "https://images.unsplash.com/photo-1582233634938-7952554868f7?q=80&w=2787&auto=format&fit=crop", "https://images.unsplash.com/photo-1598242475583-0863970de840?q=80&w=2787&auto=format&fit=crop"] },
];
const getTripByIdForDetail = (id) => tripsDataForDetail.find(trip => trip.id === id);

export default function TripDetailPage() {
  const { tripId } = useParams();
  const trip = getTripByIdForDetail(tripId);

  if (!trip) return <div className="pt-32 text-center text-xl">Trip not found! <Link to="/" className="text-[#00aaff] hover:underline">Go Home</Link></div>;

  const pageVariants = { hidden: { opacity: 0 }, visible: { opacity: 1 } };
  const galleryVariants = { hidden: {}, visible: { transition: { staggerChildren: 0.1 } } };
  const imageVariants = { hidden: { scale: 0.8, opacity: 0 }, visible: { scale: 1, opacity: 1 } };

  return (
      <motion.div variants={pageVariants} initial="hidden" animate="visible">
          <div className="h-[60vh] w-full relative"><img src={trip.imageUrl} alt={trip.title} className="w-full h-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent"></div><div className="absolute bottom-0 left-0 p-8 md:p-12 text-white"><motion.h1 initial={{ x: -20, opacity: 0 }} animate={{ x: 0, opacity: 1 }} transition={{ delay: 0.4 }} className="text-4xl md:text-6xl font-extrabold">{trip.title}</motion.h1><motion.p initial={{ x: -20, opacity: 0 }} animate={{ x: 0, opacity: 1 }} transition={{ delay: 0.6 }} className="text-xl mt-2">by {trip.author}</motion.p></div></div>
          <div className="container mx-auto px-6 md:px-12 py-16"><div className="grid grid-cols-1 lg:grid-cols-3 gap-12"><motion.div initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.8 }} className="lg:col-span-2"><div className="flex items-center space-x-6 mb-8 text-gray-500 dark:text-[#a0a0a0]"><div className="flex items-center space-x-2"><Calendar size={20}/><span className="font-semibold">{trip.date}</span></div><div className="flex items-center space-x-2"><MapPin size={20}/><span className="font-semibold">{trip.location}</span></div></div><h2 className="text-3xl font-bold text-gray-800 dark:text-[#e0e0e0] mb-4">About the Journey</h2><p className="text-lg leading-relaxed text-gray-600 dark:text-[#a0a0a0]">{trip.description}</p></motion.div><div className="lg:col-span-1"><h2 className="text-3xl font-bold text-gray-800 dark:text-[#e0e0e0] mb-4">Gallery</h2><motion.div variants={galleryVariants} initial="hidden" animate="visible" className="grid grid-cols-2 gap-4">{trip.gallery.map((imgUrl, index) => (<motion.div key={index} variants={imageVariants} className="aspect-square rounded-lg overflow-hidden shadow-lg"><img src={imgUrl} className="w-full h-full object-cover"/></motion.div>))}</motion.div></div></div><div className="text-center mt-16"><Link to="/" className="text-[#00aaff] text-lg font-semibold hover:underline">← Back to Discover</Link></div></div>
      </motion.div>
  );
}